[package]
name = "emergence"
version = "0.0.1"
edition = "2021"
description = "Takes notes"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.26"

# using master branch for global hotkeys
dioxus = { git = "https://github.com/DioxusLabs/dioxus" }
dioxus-desktop = { git = "https://github.com/DioxusLabs/dioxus" }

rusqlite = { version = "0.29.0", features = ["bundled", "chrono"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.17"

[package.metadata.bundle]
name = "Emergence"
identifier = "com.emergence.notes"
version = "0.0.1"
copyright = ""
category = "Developer Tool"
short_description = "Takes notes"
long_description = """
Takes notes
"""
