[package]
name = "emergence"
version = "0.0.1"
edition = "2021"
description = "Takes notes"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.26"
clap = { version = "4.3.11", features = ["derive"] }
const_format = "0.2.31"

# using master branch for global hotkeys
dioxus = { git = "https://github.com/DioxusLabs/dioxus" }
dioxus-desktop = { git = "https://github.com/DioxusLabs/dioxus" }

rusqlite = { version = "0.29.0", features = ["bundled", "chrono", "functions", "uuid"] }
smallvec = "1.11.0"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
uuid = { version = "1.4.0", features = ["v4"] }

[dev-dependencies]
criterion = "0.4"
tempfile = "3.6.0"

[[bench]]
name = "note_search"
harness = false

[package.metadata.bundle]
name = "Emergence"
identifier = "com.emergence.notes"
version = "0.0.1"
copyright = ""
category = "Developer Tool"
short_description = "Takes notes"
long_description = """
Takes notes
"""
